

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectname: 'Jogo'
  python.version: '3.5'


jobs:
- job: Build
  steps:
    - script: |
        pwd && ls -la
        echo "Esta funcionando até aqui"
        
      displayName: Build Application 
  
